language: c
compiler: clang
env:
  global:
    - MRUBY_CONFIG="../.travis_config.rb"
install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -q
  - sudo apt-get install -y libstdc++6 libonig-dev
  - git clone --depth 1 -b "1.1.0" "https://github.com/mruby/mruby.git" mruby
  - wget 'https://github.com/take-cheeze/mruby-clang-plugin/releases/download/travis-use/libmruby-clang-checker.so'
script:
  - cd mruby && ./minirake all test
